version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:docker pull circleci/android:api-30-node
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: USER circleci
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
